backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: ../../static/images

collections:
  - name: "blog"
    preview: false
    label: "Blog"
    label_singular: "Post"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/index"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime"  }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
